//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.04 at 07:22:18 PM CEST 
//


package pl.epsy.backend.xml.jacoco;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.Getter;

import java.util.List;


@JacksonXmlRootElement(localName = "class")
@Getter
public class Class {
    @JacksonXmlElementWrapper(useWrapping = false)
    @JacksonXmlProperty(localName = "method")
    private List<Method> methods;
    @JacksonXmlElementWrapper(useWrapping = false)
    @JacksonXmlProperty(localName = "counter")
    private List<Counter> counters;
    @JacksonXmlProperty(isAttribute = true)
    private String name;
    @JacksonXmlProperty(isAttribute = true, localName = "sourcefilename")
    private String sourceFileName;
}
