//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.04 at 07:22:18 PM CEST 
//


package pl.epsy.backend.xml.jacoco;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.Getter;

@JacksonXmlRootElement(localName = "counter")
@Getter
public class Counter {
    @JacksonXmlProperty(isAttribute = true)
    private CounterType type;
    @JacksonXmlProperty(isAttribute = true)
    private int missed;
    @JacksonXmlProperty(isAttribute = true)
    private int covered;
}
