//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.04 at 07:22:18 PM CEST 
//


package pl.epsy.backend.xml.jacoco;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.Getter;

import java.time.Instant;

@JacksonXmlRootElement(localName = "sessioninfo")
@Getter
public class SessionInfo {
    @JacksonXmlProperty(isAttribute = true)
    private String id;
    @JacksonXmlProperty(isAttribute = true)
    private Instant start;
    @JacksonXmlProperty(isAttribute = true)
    private Instant dump;
}
