spring.application.name=backend

spring.config.import=optional:classpath:messages.properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# MongoDB
spring.mongodb.uri=mongodb://mongodb:27017/appdb
spring.mongodb.database=appdb

# Server
server.port=8080

spring.devtools.remote.secret=remoteadminpass