//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.04 at 07:23:54 PM CEST 
//


package pl.epsy.backend.xml.surefire;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.Getter;

import java.util.List;

@JacksonXmlRootElement(localName = "testsuite")
@Getter
public class TestSuite {
    @JacksonXmlProperty(isAttribute = true, localName = "noNamespaceSchemaLocation")
    private String schemaLocation;
    @JacksonXmlProperty(isAttribute = true, localName = "schemaLocation")
    private String xsiSchemaLocation;
    private Properties properties;
    @JacksonXmlElementWrapper(useWrapping = false)
    @JacksonXmlProperty(localName = "testcase")
    private List<TestCase> testcases;
    @JacksonXmlProperty(isAttribute = true)
    private String version;
    @JacksonXmlProperty(isAttribute = true)
    private String name;
    @JacksonXmlProperty(isAttribute = true)
    private Float time;
    @JacksonXmlProperty(isAttribute = true)
    private Integer tests;
    @JacksonXmlProperty(isAttribute = true)
    private Integer errors;
    @JacksonXmlProperty(isAttribute = true)
    private Integer skipped;
    @JacksonXmlProperty(isAttribute = true)
    private Integer failures;
    @JacksonXmlProperty(isAttribute = true)
    private String group;
}
